version: '3.8'

services:

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"  # LocalStack exposes services on port 4566
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1

  aws-cli:
    image: amazon/aws-cli
    depends_on:
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    entrypoint: /bin/sh -c
    command: >
      "
        until aws --endpoint-url=http://localstack:4566 s3api list-buckets; do sleep 1; done;
        aws --endpoint-url=http://localstack:4566 s3api create-bucket --bucket image-bucket --region us-east-1
      "

  api:
    build: .
    image: restaurant-review-api:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/reviewdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=reviewdb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql


volumes:
  db_data: