openapi: 3.0.3
servers:
  - url: http://localhost:8080
info:
  title: Restaurant Review REST API
  version: 1.0.0
  description: Spring Boot Restaurant Review REST API Documentation
  contact:
    name: Elizabeth Drew
paths:
  /api/v1/restaurants:
    get:
      security: []
      summary: Get all restaurants
      operationId: getAllRestaurants
      tags:
        - Restaurants
      description: Returns a list of all restaurants.
      parameters:
        - name: city
          in: query
          description: The city to filter restaurants by.
          required: false
          schema:
            type: string
        - name: rating
          in: query
          description: The rating value to filter restaurants by.
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 5
        - name: user_id
          in: query
          description: The user ID to filter restaurants by.
          required: false
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A list of restaurants.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Restaurant'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/restaurant/add:
    post:
      summary: Add a new restaurant
      operationId: addNewRestaurant
      tags:
        - Restaurants
      description: Adds a new restaurant to the database.
      security:
        - basicAuth: []
      requestBody:
        description: The restaurant to add.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RestaurantInput'
      responses:
        '201':
          description: The new restaurant
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Restaurant'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/restaurant/{restaurantId}:
    get:
      security: []
      summary: Get a restaurant by ID
      operationId: getRestaurantById
      description: Returns a single restaurant by ID.
      tags:
        - Restaurants
      parameters:
        - name: restaurantId
          in: path
          description: The ID of the restaurant to retrieve.
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: The restaurant.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Restaurant'

  /api/v1/restaurant/{restaurantId}/edit:
    put:
      summary: Update a restaurant
      operationId: updateRestaurantById
      description: Updates a restaurant by ID.
      security:
        - basicAuth: []
      tags:
        - Restaurants
      parameters:
        - name: restaurantId
          in: path
          description: The ID of the restaurant to update.
          required: true
          schema:
            type: integer
            minimum: 1
      requestBody:
        description: The updated restaurant.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RestaurantInput'
      responses:
        '200':
          description: The updated restaurant.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Restaurant'

  /api/v1/restaurant/{restaurantId}/delete:
    delete:
      summary: Delete a restaurant
      operationId: deleteRestaurantById
      tags:
        - Restaurants
      description: Deletes a restaurant by ID.
      security:
        - basicAuth: []
      parameters:
        - name: restaurantId
          in: path
          description: The ID of the restaurant to delete.
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '204':
          description: Restaurant deleted successfully.
        '404':
          description: Restaurant not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/signup:
    post:
      summary: Add a new user
      tags:
        - User
      description: Adds a new user to the database.
      operationId: addUser
      security:
        - basicAuth: []
      requestBody:
        description: The user to add.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '201':
          description: The new user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/user/{userId}:

    get:
      summary: Get a user by ID
      tags:
        - User
      description: Returns a single user by ID
      operationId: getUserById
      security:
        - basicAuth: []
      parameters:
        - name: userId
          in: path
          description: The ID or name of the user to retrieve.
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: The user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/user/{userId}/edit:
    put:
      summary: Update a user
      tags:
        - User
      description: Updates a user by ID.
      operationId: updateUserById
      security:
        - basicAuth: []
      parameters:
        - name: userId
          in: path
          description: The ID or name of the user to retrieve.
          required: true
          schema:
            type: integer
            minimum: 1
      requestBody:
        description: The updated user.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '200':
          description: The updated user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/user/{userId}/delete:
    delete:
      summary: Delete a user by ID
      tags:
        - User
      operationId: deleteUserById
      security:
        - basicAuth: []
      parameters:
        - name: userId
          in: path
          description: The ID or name of the user to retrieve.
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '204':
          description: User deleted
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/reviews:
    get:
      security: []
      summary: Get all reviews
      operationId: getAllReviews
      tags:
        - Reviews
      description: Returns a list of all reviews.
      parameters:
        - name: restaurant_id
          in: query
          description: The restaurant ID to filter reviews by.
          required: false
          schema:
            type: integer
            format: int64
        - name: user_id
          in: query
          description: The user ID to filter reviews by.
          required: false
          schema:
            type: integer
            format: int64
        - name: rating
          in: query
          description: The rating value to filter restaurants by.
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 5
      responses:
        '200':
          description: A list of reviews.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Review'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/review/add:
    post:
      summary: Add a new review
      operationId: addNewReview
      tags:
        - Reviews
      description: Adds a new review to the database.
      security:
        - basicAuth: [ ]
      requestBody:
        description: The review to add.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReviewInput'
      responses:
        '201':
          description: The new review
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/review/{reviewId}:
    get:
      security: []
      summary: Get a review by ID
      operationId: getReviewById
      tags:
        - Reviews
      description: Returns a single review by ID.
      parameters:
        - name: reviewId
          in: path
          description: The ID of the review to retrieve.
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: The review.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        '404':
          description: Review not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/review/{reviewId}/edit:
    put:
      summary: Update a review
      operationId: updateReviewById
      tags:
        - Reviews
      description: Updates a review by ID.
      security:
        - basicAuth: [ ]
      parameters:
        - name: reviewId
          in: path
          description: The ID of the review to update.
          required: true
          schema:
            type: integer
            minimum: 1
      requestBody:
        description: The updated review data.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReviewInput'
      responses:
        '200':
          description: The updated review.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        '400':
          description: Invalid input.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Review not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/review/{reviewId}/delete:
    delete:
      summary: Delete a review
      operationId: deleteReviewById
      description: Deletes a review by ID.
      security:
        - basicAuth: [ ]
      tags:
        - Reviews
      parameters:
        - name: reviewId
          in: path
          description: The ID of the review to delete.
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '204':
          description: Successfully deleted.
        '404':
          description: Review not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:

  securitySchemes:
    basicAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    idParam:
      name: id
      in: path
      description: The ID of the resource to retrieve or update.
      required: true
      schema:
        type: integer
        format: int64

    nameParam:
      name: name
      in: query
      description: The name of the resource to search for.
      required: false
      schema:
        type: string

    cityParam:
      name: city
      in: query
      description: The city of the resource to search for.
      required: false
      schema:
        type: string

    ratingParam:
      name: rating
      in: query
      description: The rating of the resource to search for.
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 5

  schemas:

    Review:
      type: object
      properties:
        id:
          type: integer
          format: int64
        restaurant_id:
          type: integer
          format: int64
        restaurant_name:
          type: string
        restaurant_city:
          type: string
        user_id:
          type: integer
          format: int64
        rating:
          type: integer
          minimum: 1
          maximum: 5
        comment:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - restaurant_id
        - user_id
        - rating
        - restaurant_name
        - restaurant_city

    ReviewInput:
      type: object
      properties:
        restaurant_id:
          type: integer
          format: int64
        rating:
          type: integer
          minimum: 1
          maximum: 5
        comment:
          type: string
      required:
        - restaurant_id
        - rating
        - comment

    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: The unique identifier of the user.
        name:
          type: string
          description: The name of the user.
        email:
          type: string
          description: The email address of the user.
        username:
          type: string
          description: The username of the user.
        password:
          type: string
          description: The password of the user.
        role:
          type: string
          description: The role of the user (admin or reviewer)
          enum: ['ADMIN', 'REVIEWER']
        created_at:
          type: string
          format: date-time
          description: The date and time the user was created.
      required:
        - username
        - name
        - email
        - password
        - role

    UserInput:
      type: object
      properties:
        name:
          type: string
          description: The name of the user.
        email:
          type: string
          description: The email address of the user.
        username:
          type: string
          description: The username of the user.
        password:
          type: string
          description: The password of the user.
        role:
          type: string
          description: The role of the user (admin or reviewer)
          enum: [ 'ADMIN', 'REVIEWER' ]
          default: 'REVIEWER'
      required:
        - name
        - email
        - password
        - username
        - role

    Restaurant:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: The unique identifier of the restaurant.
        name:
          type: string
          description: The name of the restaurant.
        city:
          type: string
          description: The city where the restaurant is located.
        rating:
          type: integer
          minimum: 1
          maximum: 5
          description: The rating of the restaurant.
        created_at:
          type: string
          format: date-time
          description: The date and time the restaurant was created.
        user_id:
          type: integer
          format: int64
      required:
        - name
        - city
        - rating

    RestaurantInput:
      type: object
      properties:
        name:
          type: string
          description: The name of the restaurant.
        city:
          type: string
          description: The city where the restaurant is located.
      required:
        - name
        - city

    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required:
        - code
        - message
