spring:
  config:
    activate:
      on-profile: default
  datasource:
    generate-unique-name: false
    name: reviewSystem
    url: jdbc:mysql://localhost:3306/reviewdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: admin
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    contexts: standard
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    dev.drew.restaurantreview: DEBUG

---
spring:
  config:
    activate:
      on-profile: local
  liquibase:
    contexts: standard, seed
