spring:
  config:
    activate:
      on-profile: default
  datasource:
    generate-unique-name: false
    name: reviewSystem
    url: jdbc:mysql://localhost:3306/reviewdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: admin
    password: password
  jpa:
    properties:
      hibernate:
        search:
          backend:
            directory:
              root: ./data/index
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    contexts: standard
  servlet:
    multipart:
      enabled: true
      max-file-size: 12MB
      max-request-size: 12MB

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    dev.drew.restaurantreview: DEBUG

server:
  forward-headers-strategy: framework

---
spring:
  config:
    activate:
      on-profile: local
  liquibase:
    contexts: standard, seed

aws:
  s3:
    bucket: "image-bucket"
