spring:
  datasource:
    generate-unique-name: false
    name: reviewSystem
    url: jdbc:mysql://localhost:3306/reviewdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: admin
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.yml
logging:
  level:
    root: INFO
    org:
      springframework.web: WARN
      hibernate: ERROR
